markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough"]
hilighter:        true

permalink:        pretty

title:            Container42
tagline:          Stuff I find interesting
url:              https://www.container42.com
paginate:         5
baseurl:          /
author:
  name:           Brian Goff
  url:            https://www.container42.com
  twitter:        https://twitter.com/cpuguy83
  email:          cpuguy83@gmail.com
  github:         https://github.com/cpuguy83

version: 1

github:
  repo: //github.com/cpuguy83/blog

comments: true

disqus:
  short_name: tech-d

google:
  analytics_id: UA-15812340-1

exclude: [Dockerfile, site.conf]
